Repository KNU-Hackerton-Team-Gongdae9/server, pull requests merged in 2021-07, with the labels that each got.

#5 FEAT: ADD Member domain
  .DS_Store
  src/main/java/com/knu/community/Response.java
  src/main/java/com/knu/community/base/BaseEntity.java
  src/main/java/com/knu/community/base/BaseTimeEntity.java
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/email/service/EmailService.java
  src/main/java/com/knu/community/email/service/MemberDetailsService.java
  src/main/java/com/knu/community/email/util/CookieUtil.java
  src/main/java/com/knu/community/email/util/JwtRequestFilter.java
  src/main/java/com/knu/community/email/util/JwtUtil.java
  src/main/java/com/knu/community/email/util/RedisUtil.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/member/domain/Major.java
  src/main/java/com/knu/community/member/domain/Member.java
  src/main/java/com/knu/community/member/domain/MemberRole.java
  src/main/java/com/knu/community/member/dto/RequestVerifyEmail.java
  src/main/java/com/knu/community/member/dto/SignInForm.java
  src/main/java/com/knu/community/member/dto/SignUpForm.java
  src/main/java/com/knu/community/member/dto/SignUpFormValidator.java
  src/main/java/com/knu/community/member/repository/MemberRepository.java
  src/main/java/com/knu/community/member/security/SecurityMember.java
Labels: Establish

#7 FEAT: Board, Comment, WriteBoard, WriteCommnet 도메인 구현
  src/main/java/com/knu/community/CommunityApplication.java
  src/main/java/com/knu/community/board/domain/Board.java
  src/main/java/com/knu/community/board/domain/Category.java
  src/main/java/com/knu/community/board/domain/WriteBoard.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/domain/WriteComment.java
  src/main/java/com/knu/community/domain/Reply.java
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/email/util/JwtRequestFilter.java
  src/main/java/com/knu/community/member/domain/Member.java
Labels: Establish

#11 FEAT: NotFoundException Add
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/domain/Board.java
  src/main/java/com/knu/community/board/domain/WriteBoard.java
  src/main/java/com/knu/community/board/dto/BoardForm.java
  src/main/java/com/knu/community/board/repository/BoardRepository.java
  src/main/java/com/knu/community/board/repository/WriteBoardRepository.java
  src/main/java/com/knu/community/board/service/BoardService.java
  src/main/java/com/knu/community/error/ErrorCode.java
  src/main/java/com/knu/community/error/GlobalExceptionHandler.java
  src/main/java/com/knu/community/error/NotFoundException.java
Labels: enhancement

#15 FIX: Reply 패키지 구조 변경
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/repository/CommentRepository.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/reply/domain/Reply.java
  src/main/java/com/knu/community/reply/repository/ReplyRepository.java
Labels: bug

#16 FEAT: Commnet 관련 서비스 추가(댓글작성)
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/domain/WriteComment.java
  src/main/java/com/knu/community/comment/dto/CommentForm.java
  src/main/java/com/knu/community/comment/repository/WriteCommentRepository.java
  src/main/java/com/knu/community/comment/service/CommentService.java
Labels: enhancement

#20 FIX : Reply 인스턴스 생성시에ReplyForm 대신 Comment의 속성으로 지정했던걸 고침
  src/main/java/com/knu/community/reply/domain/Reply.java
Labels: bug

#21 FEAT: Board,Comment Update
  src/main/java/com/knu/community/board/domain/Board.java
  src/main/java/com/knu/community/board/service/BoardService.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/service/CommentService.java
Labels: enhancement

#23 FEAT: JWT Claim 수정 및 복호화 기능 구현
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/config/SecurityConfig.java
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/email/service/MemberDetailsService.java
  src/main/java/com/knu/community/email/util/JwtRequestFilter.java
  src/main/java/com/knu/community/email/util/JwtUtil.java
  src/main/java/com/knu/community/member/controller/MemberController.java
Labels: bug, enhancement

#24 FIX: SingInForm,SignUpForm bug fix
  src/main/java/com/knu/community/comment/repository/CommentRepository.java
  src/main/java/com/knu/community/member/dto/SignInForm.java
  src/main/java/com/knu/community/member/dto/SignUpForm.java
Labels: bug

#26 FIX: 게시판 작성부터 댓글, 답글 작성 기능 작동 완료
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/domain/Board.java
  src/main/java/com/knu/community/board/domain/WriteBoard.java
  src/main/java/com/knu/community/board/repository/BoardRepository.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/domain/WriteComment.java
  src/main/java/com/knu/community/comment/service/CommentService.java
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/member/domain/Member.java
  src/main/java/com/knu/community/reply/domain/Reply.java
  src/test/java/com/knu/community/BoardTest.java
Labels: bug

#31 FIX: API 반환형태 통일 및 Exception Handling
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/service/BoardService.java
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/email/service/MemberDetailsService.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/member/domain/Member.java
  src/main/java/com/knu/community/member/dto/SignUpForm.java
  src/main/java/com/knu/community/member/repository/MemberRepository.java
  src/test/java/com/knu/community/BoardTest.java
Labels: bug, enhancement

#33 FEAT: 내가 작성한 게시물, 댓글, 답글 조회 기능 구현
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/repository/BoardRepository.java
  src/main/java/com/knu/community/board/service/BoardService.java
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/comment/repository/CommentRepository.java
  src/main/java/com/knu/community/comment/service/CommentService.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/member/repository/MemberRepository.java
  src/main/java/com/knu/community/reply/controller/ReplyController.java
  src/main/java/com/knu/community/reply/repository/ReplyRepository.java
  src/main/java/com/knu/community/reply/service/GetReplyService.java
  src/test/java/com/knu/community/BoardTest.java
Labels: enhancement

#34 FIX: commentDTO추가 및 ResponseEntity로 리턴타입 통일
  src/main/java/com/knu/community/board/domain/WriteBoard.java
  src/main/java/com/knu/community/board/dto/BoardForm.java
  src/main/java/com/knu/community/board/repository/WriteBoardRepository.java
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/comment/domain/WriteComment.java
  src/main/java/com/knu/community/comment/dto/CommentDto.java
  src/main/java/com/knu/community/comment/dto/CommentForm.java
  src/main/java/com/knu/community/comment/repository/WriteCommentRepository.java
  src/main/java/com/knu/community/comment/service/CommentService.java
  src/main/java/com/knu/community/member/domain/Member.java
  src/test/java/com/knu/community/BoardTest.java
Labels: bug

#35 FIX: BoardController 충돌해결
  src/main/java/com/knu/community/board/controller/BoardController.java
Labels: bug

#36 FEAT: BoardService(내용검색 제목검색) 기능 추가 및 수정
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/dto/BoardForm.java
  src/main/java/com/knu/community/board/repository/BoardRepository.java
  src/main/java/com/knu/community/board/service/BoardService.java
Labels: bug, enhancement

#37 FIX: 오탈자 수정 및 메일 인증 수정
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/email/service/AuthService.java
Labels: bug

#38 FIX: 회원가입 시 JWT 토큰을 요청에서 못 받는 에러 해결
  src/main/java/com/knu/community/email/service/AuthService.java
  src/main/java/com/knu/community/profile/controller/ProfileController.java
Labels: bug

#43 FIX: 등록한 게시물, 댓글, 답글 모두 조회 정상 구현
  src/main/java/com/knu/community/board/controller/BoardController.java
  src/main/java/com/knu/community/board/dto/BoardDetailDto.java
  src/main/java/com/knu/community/board/repository/BoardRepository.java
  src/main/java/com/knu/community/board/service/BoardService.java
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/comment/domain/Comment.java
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/test/java/com/knu/community/BoardTest.java
Labels: bug

#49 FIX : BoardDto 에 기본키 추가
  src/main/java/com/knu/community/board/dto/BoardDto.java
Labels: bug

#50 FIX: 생성자 에러 수정
  src/main/java/com/knu/community/board/dto/BoardDto.java
Labels: bug

#51 FIX : DTO 생성자 에러 수정
  src/main/java/com/knu/community/comment/dto/CommentDto.java
Labels: bug

#52 FIX: 기본 키 오류 해결
  src/main/java/com/knu/community/comment/dto/CommentDto.java
  src/main/java/com/knu/community/comment/service/CommentService.java
Labels: bug

#53 FEAT: 팀 프로젝트 게시판 추가
  src/main/java/com/knu/community/board/domain/Category.java
Labels: enhancement

#57 FIX: Reply 반환 시 DTO로 기본 키 포함 반환
  src/main/java/com/knu/community/reply/controller/ReplyController.java
  src/main/java/com/knu/community/reply/domain/Reply.java
  src/main/java/com/knu/community/reply/dto/ReplyDto.java
  src/main/java/com/knu/community/reply/service/EditReplyService.java
  src/main/java/com/knu/community/reply/service/WriteReplyService.java
Labels: bug

#59 FEAT: 스터디 카테고리 추가
  src/main/java/com/knu/community/board/domain/Category.java
Labels: enhancement

#62 FEAT: 댓글 수정 삭제 기능 구현
  src/main/java/com/knu/community/comment/controller/CommentController.java
  src/main/java/com/knu/community/comment/service/CommentService.java
Labels: enhancement

#66 FIX: 이메일과 닉네임을 반환하는 DTO 추가
  src/main/java/com/knu/community/member/controller/MemberController.java
  src/main/java/com/knu/community/member/domain/MemberDto.java
Labels: enhancement
